"""Atomic artifact writers for diarization outputs."""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from typing import Any

from .diarization_models import (
    AttributedTranscript,
    DiarizationDiagnostics,
    DiarizationTimeline,
    OverlapRegion,
    SpeakerProfile,
)


def diarization_artifacts_dir(job_dir: Path) -> Path:
    return job_dir / "artifacts" / "diarization"


def atomic_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_path = tempfile.mkstemp(dir=str(path.parent), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(temp_path, str(path))
    except Exception:
        if os.path.exists(temp_path):
            try:
                os.unlink(temp_path)
            except OSError:
                pass
        raise


def atomic_write_json(path: Path, data: Any) -> None:
    atomic_write_text(path, json.dumps(data, ensure_ascii=False, indent=2))


def timeline_to_rttm(timeline: DiarizationTimeline, uri: str = "audio") -> str:
    lines: list[str] = []
    for turn in timeline.turns:
        duration = max(0.0, turn.end - turn.start)
        lines.append(
            f"SPEAKER {turn.speaker_id}\t1\t{turn.start:.3f}\t{duration:.3f}\t"
            f"<NA>\t<NA>\t{turn.speaker_id}\t<NA>\t<NA>"
        )
    header = f";; RTTM generated by DouyinVietnamizer ({timeline.backend})\n"
    return header + "\n".join(lines) + ("\n" if lines else "")


def write_diarization_artifacts(
    job_dir: Path,
    *,
    regular: DiarizationTimeline,
    exclusive: DiarizationTimeline,
    attributed: AttributedTranscript,
    overlap_regions: list[OverlapRegion],
    speaker_profiles: list[SpeakerProfile],
    diagnostics: DiarizationDiagnostics,
) -> Path:
    root = diarization_artifacts_dir(job_dir)
    root.mkdir(parents=True, exist_ok=True)

    atomic_write_text(root / "regular.rttm", timeline_to_rttm(regular))
    atomic_write_text(root / "exclusive.rttm", timeline_to_rttm(exclusive))
    atomic_write_json(root / "regular.json", regular.model_dump())
    atomic_write_json(root / "exclusive.json", exclusive.model_dump())
    atomic_write_json(root / "attributed_transcript.json", attributed.model_dump())
    atomic_write_json(
        root / "overlap_regions.json",
        [region.model_dump() for region in overlap_regions],
    )
    atomic_write_json(
        root / "speaker_profiles.json",
        [profile.model_dump() for profile in speaker_profiles],
    )
    atomic_write_json(root / "diagnostics.json", diagnostics.model_dump())
    return root
